version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Instalando dependências..."
      - pip install -r requirements.txt
      - playwright install --with-deps chromium
      - npm install -g allure-commandline

  build:
    commands:
      - echo "Iniciando os testes..."
      - |
        pytest \
        tests/test_initial.py \
        tests/web/test_single_orders.py \
        tests/web/test_order_management.py \
        tests/web/test_table_operations.py \
        --alluredir=allure-results \
        -v ; \
        TEST_EXIT_CODE=$?
      
      - echo "Os testes terminaram. Código de saída $TEST_EXIT_CODE"

      - echo "Gerando relatório Allure..."
      - allure generate allure-results -o allure-report --clean

      - echo "Publicando no S3..."
      - aws s3 sync allure-report/ s3://relatorios-testes-qa-playwright-2026 --delete
      
      - |
        if [ $TEST_EXIT_CODE -ne 0 ]; then
          echo "FALHA CRÍTICA Testes não passaram. Bloqueando o pipeline."
          exit $TEST_EXIT_CODE
        else
          echo "SUCESSO Todos os testes passaram."
        fi
