version: "3.9"

services:
  playwright-tests:
    build: .
    container_name: playwright-tests
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
    restart: unless-stopped
    ports:
         - "8080:8080"
